feat: Add build ID validation and error handling in version checking script

diff --git a/.github/workflows/fetch_gamedata.yml b/.github/workflows/fetch_gamedata.yml
--- a/.github/workflows/fetch_gamedata.yml
+++ b/.github/workflows/fetch_gamedata.yml
@@ -74,10 +74,12 @@ jobs:
                   echo "Error: Current Gamedata is up to date. Abort." >&2
                   exit 1
                 fi
-
                 break
               fi
             done <<< "$configs"
+          else
+            echo "Error: Build ID file not found at $GITHUB_WORKSPACE/mods/core.stormmod/base.stormdata/buildid.txt" >&2
+            exit 1
           fi
 
           echo "Github Action Output:"
